driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-28
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
- name: default
  run_list:
  - recipe[ssh_known_hosts_test]
  attributes: {}
- name: cacher
  run_list:
  - recipe[ssh_known_hosts_test::cacher]
  attributes: {}
- name: cacher-client
  run_list:
  - recipe[ssh_known_hosts_test::default]
  attributes:
    ssh_known_hosts:
      use_data_bag_cache: true
- name: resource
  run_list:
  - recipe[ssh_known_hosts_test::resource]
